/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as test from "./test";
export type { test };
export type { Greeter } from "./Greeter";
export type { IWorkFi } from "./IWorkFi";
export type { WorkFi } from "./WorkFi";
