/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type BountyMetadataStruct = {
  workerStablePay: PromiseOrValue<BigNumberish>;
  workerNativePay: PromiseOrValue<BigNumberish>;
  exchangeRate: PromiseOrValue<BigNumberish>;
  stablecoin: PromiseOrValue<string>;
  nativeToken: PromiseOrValue<string>;
  dailyYieldPercentage: PromiseOrValue<BigNumberish>;
  worker: PromiseOrValue<string>;
  recruiter: PromiseOrValue<string>;
  status: PromiseOrValue<BigNumberish>;
  workerDeadline: PromiseOrValue<BigNumberish>;
  initialWorkerStablePay: PromiseOrValue<BigNumberish>;
  initialWorkerNativePay: PromiseOrValue<BigNumberish>;
  creationDate: PromiseOrValue<BigNumberish>;
};

export type BountyMetadataStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  string,
  BigNumber,
  string,
  string,
  number,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  workerStablePay: BigNumber;
  workerNativePay: BigNumber;
  exchangeRate: BigNumber;
  stablecoin: string;
  nativeToken: string;
  dailyYieldPercentage: BigNumber;
  worker: string;
  recruiter: string;
  status: number;
  workerDeadline: BigNumber;
  initialWorkerStablePay: BigNumber;
  initialWorkerNativePay: BigNumber;
  creationDate: BigNumber;
};

export declare namespace IWorkFi {
  export type InvestmentMetadataStruct = {
    stableAmount: PromiseOrValue<BigNumberish>;
    nativeTokenPayment: PromiseOrValue<BigNumberish>;
  };

  export type InvestmentMetadataStructOutput = [BigNumber, BigNumber] & {
    stableAmount: BigNumber;
    nativeTokenPayment: BigNumber;
  };
}

export interface WorkFiInterface extends utils.Interface {
  functions: {
    "acceptInvestorPayment(uint256)": FunctionFragment;
    "acceptWorker(uint256,address)": FunctionFragment;
    "acceptWorkerPayment(uint256)": FunctionFragment;
    "addStablecoinToWhitelist(address)": FunctionFragment;
    "calculateYieldPool(uint128,uint128,uint256,uint256)": FunctionFragment;
    "cancelBounty(uint256)": FunctionFragment;
    "createBounty(uint128,uint128,uint96,address,address,uint128,uint256)": FunctionFragment;
    "getAmountOfInvestments(uint256)": FunctionFragment;
    "getBounty(uint256)": FunctionFragment;
    "getInvestment(uint256,uint256)": FunctionFragment;
    "invest(uint256,uint128)": FunctionFragment;
    "markBountyAsCompleted(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "removeStablecoinFromWhitelist(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdrawInvestments(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptInvestorPayment"
      | "acceptWorker"
      | "acceptWorkerPayment"
      | "addStablecoinToWhitelist"
      | "calculateYieldPool"
      | "cancelBounty"
      | "createBounty"
      | "getAmountOfInvestments"
      | "getBounty"
      | "getInvestment"
      | "invest"
      | "markBountyAsCompleted"
      | "owner"
      | "removeStablecoinFromWhitelist"
      | "renounceOwnership"
      | "transferOwnership"
      | "withdrawInvestments"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptInvestorPayment",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptWorker",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptWorkerPayment",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "addStablecoinToWhitelist",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateYieldPool",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBounty",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createBounty",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountOfInvestments",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getBounty",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestment",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "invest",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "markBountyAsCompleted",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeStablecoinFromWhitelist",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawInvestments",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptInvestorPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptWorker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptWorkerPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addStablecoinToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateYieldPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountOfInvestments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBounty", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "invest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markBountyAsCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeStablecoinFromWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawInvestments",
    data: BytesLike
  ): Result;

  events: {
    "BountyCancelled(uint256)": EventFragment;
    "BountyCompleted(uint256)": EventFragment;
    "BountyCreated(uint256,address)": EventFragment;
    "Invested(uint256,address,uint128)": EventFragment;
    "InvestmentsWithdrawn(uint256)": EventFragment;
    "InvestorPaymentAccepted(uint256,uint128)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "StablecoinAddedToWhitelist(address)": EventFragment;
    "StablecoinRemovedFromWhitelist(address)": EventFragment;
    "WorkerAccepted(uint256,address)": EventFragment;
    "WorkerPaymentAccepted(uint256,uint128,uint128)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BountyCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BountyCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BountyCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Invested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InvestmentsWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InvestorPaymentAccepted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StablecoinAddedToWhitelist"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "StablecoinRemovedFromWhitelist"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WorkerAccepted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WorkerPaymentAccepted"): EventFragment;
}

export interface BountyCancelledEventObject {
  bountyId: BigNumber;
}
export type BountyCancelledEvent = TypedEvent<
  [BigNumber],
  BountyCancelledEventObject
>;

export type BountyCancelledEventFilter = TypedEventFilter<BountyCancelledEvent>;

export interface BountyCompletedEventObject {
  bountyId: BigNumber;
}
export type BountyCompletedEvent = TypedEvent<
  [BigNumber],
  BountyCompletedEventObject
>;

export type BountyCompletedEventFilter = TypedEventFilter<BountyCompletedEvent>;

export interface BountyCreatedEventObject {
  bountyId: BigNumber;
  recruiter: string;
}
export type BountyCreatedEvent = TypedEvent<
  [BigNumber, string],
  BountyCreatedEventObject
>;

export type BountyCreatedEventFilter = TypedEventFilter<BountyCreatedEvent>;

export interface InvestedEventObject {
  bountyId: BigNumber;
  investor: string;
  amount: BigNumber;
}
export type InvestedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  InvestedEventObject
>;

export type InvestedEventFilter = TypedEventFilter<InvestedEvent>;

export interface InvestmentsWithdrawnEventObject {
  bountyId: BigNumber;
}
export type InvestmentsWithdrawnEvent = TypedEvent<
  [BigNumber],
  InvestmentsWithdrawnEventObject
>;

export type InvestmentsWithdrawnEventFilter =
  TypedEventFilter<InvestmentsWithdrawnEvent>;

export interface InvestorPaymentAcceptedEventObject {
  bountyId: BigNumber;
  payment: BigNumber;
}
export type InvestorPaymentAcceptedEvent = TypedEvent<
  [BigNumber, BigNumber],
  InvestorPaymentAcceptedEventObject
>;

export type InvestorPaymentAcceptedEventFilter =
  TypedEventFilter<InvestorPaymentAcceptedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface StablecoinAddedToWhitelistEventObject {
  stablecoin: string;
}
export type StablecoinAddedToWhitelistEvent = TypedEvent<
  [string],
  StablecoinAddedToWhitelistEventObject
>;

export type StablecoinAddedToWhitelistEventFilter =
  TypedEventFilter<StablecoinAddedToWhitelistEvent>;

export interface StablecoinRemovedFromWhitelistEventObject {
  stablecoin: string;
}
export type StablecoinRemovedFromWhitelistEvent = TypedEvent<
  [string],
  StablecoinRemovedFromWhitelistEventObject
>;

export type StablecoinRemovedFromWhitelistEventFilter =
  TypedEventFilter<StablecoinRemovedFromWhitelistEvent>;

export interface WorkerAcceptedEventObject {
  bountyId: BigNumber;
  worker: string;
}
export type WorkerAcceptedEvent = TypedEvent<
  [BigNumber, string],
  WorkerAcceptedEventObject
>;

export type WorkerAcceptedEventFilter = TypedEventFilter<WorkerAcceptedEvent>;

export interface WorkerPaymentAcceptedEventObject {
  bountyId: BigNumber;
  nativePay: BigNumber;
  stablePay: BigNumber;
}
export type WorkerPaymentAcceptedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  WorkerPaymentAcceptedEventObject
>;

export type WorkerPaymentAcceptedEventFilter =
  TypedEventFilter<WorkerPaymentAcceptedEvent>;

export interface WorkFi extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WorkFiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptInvestorPayment(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    acceptWorker(
      bountyId: PromiseOrValue<BigNumberish>,
      worker: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    acceptWorkerPayment(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addStablecoinToWhitelist(
      stablecoin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    calculateYieldPool(
      workerNativePay: PromiseOrValue<BigNumberish>,
      dailyYieldPercentage: PromiseOrValue<BigNumberish>,
      bountyCreationDate: PromiseOrValue<BigNumberish>,
      workerDeadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    cancelBounty(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createBounty(
      workerStablePay: PromiseOrValue<BigNumberish>,
      workerNativePay: PromiseOrValue<BigNumberish>,
      exchangeRate: PromiseOrValue<BigNumberish>,
      nativeToken: PromiseOrValue<string>,
      stablecoin: PromiseOrValue<string>,
      dailyYieldPercentage: PromiseOrValue<BigNumberish>,
      workerDeadline: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAmountOfInvestments(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getBounty(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BountyMetadataStructOutput]>;

    getInvestment(
      bountyId: PromiseOrValue<BigNumberish>,
      investmentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[IWorkFi.InvestmentMetadataStructOutput]>;

    invest(
      bountyId: PromiseOrValue<BigNumberish>,
      stableAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    markBountyAsCompleted(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    removeStablecoinFromWhitelist(
      stablecoin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawInvestments(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  acceptInvestorPayment(
    bountyId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  acceptWorker(
    bountyId: PromiseOrValue<BigNumberish>,
    worker: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  acceptWorkerPayment(
    bountyId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addStablecoinToWhitelist(
    stablecoin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  calculateYieldPool(
    workerNativePay: PromiseOrValue<BigNumberish>,
    dailyYieldPercentage: PromiseOrValue<BigNumberish>,
    bountyCreationDate: PromiseOrValue<BigNumberish>,
    workerDeadline: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  cancelBounty(
    bountyId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createBounty(
    workerStablePay: PromiseOrValue<BigNumberish>,
    workerNativePay: PromiseOrValue<BigNumberish>,
    exchangeRate: PromiseOrValue<BigNumberish>,
    nativeToken: PromiseOrValue<string>,
    stablecoin: PromiseOrValue<string>,
    dailyYieldPercentage: PromiseOrValue<BigNumberish>,
    workerDeadline: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAmountOfInvestments(
    bountyId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getBounty(
    bountyId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BountyMetadataStructOutput>;

  getInvestment(
    bountyId: PromiseOrValue<BigNumberish>,
    investmentId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IWorkFi.InvestmentMetadataStructOutput>;

  invest(
    bountyId: PromiseOrValue<BigNumberish>,
    stableAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  markBountyAsCompleted(
    bountyId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  removeStablecoinFromWhitelist(
    stablecoin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawInvestments(
    bountyId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptInvestorPayment(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    acceptWorker(
      bountyId: PromiseOrValue<BigNumberish>,
      worker: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    acceptWorkerPayment(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    addStablecoinToWhitelist(
      stablecoin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    calculateYieldPool(
      workerNativePay: PromiseOrValue<BigNumberish>,
      dailyYieldPercentage: PromiseOrValue<BigNumberish>,
      bountyCreationDate: PromiseOrValue<BigNumberish>,
      workerDeadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelBounty(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createBounty(
      workerStablePay: PromiseOrValue<BigNumberish>,
      workerNativePay: PromiseOrValue<BigNumberish>,
      exchangeRate: PromiseOrValue<BigNumberish>,
      nativeToken: PromiseOrValue<string>,
      stablecoin: PromiseOrValue<string>,
      dailyYieldPercentage: PromiseOrValue<BigNumberish>,
      workerDeadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAmountOfInvestments(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBounty(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BountyMetadataStructOutput>;

    getInvestment(
      bountyId: PromiseOrValue<BigNumberish>,
      investmentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IWorkFi.InvestmentMetadataStructOutput>;

    invest(
      bountyId: PromiseOrValue<BigNumberish>,
      stableAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    markBountyAsCompleted(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    removeStablecoinFromWhitelist(
      stablecoin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawInvestments(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BountyCancelled(uint256)"(
      bountyId?: PromiseOrValue<BigNumberish> | null
    ): BountyCancelledEventFilter;
    BountyCancelled(
      bountyId?: PromiseOrValue<BigNumberish> | null
    ): BountyCancelledEventFilter;

    "BountyCompleted(uint256)"(
      bountyId?: PromiseOrValue<BigNumberish> | null
    ): BountyCompletedEventFilter;
    BountyCompleted(
      bountyId?: PromiseOrValue<BigNumberish> | null
    ): BountyCompletedEventFilter;

    "BountyCreated(uint256,address)"(
      bountyId?: PromiseOrValue<BigNumberish> | null,
      recruiter?: PromiseOrValue<string> | null
    ): BountyCreatedEventFilter;
    BountyCreated(
      bountyId?: PromiseOrValue<BigNumberish> | null,
      recruiter?: PromiseOrValue<string> | null
    ): BountyCreatedEventFilter;

    "Invested(uint256,address,uint128)"(
      bountyId?: PromiseOrValue<BigNumberish> | null,
      investor?: PromiseOrValue<string> | null,
      amount?: null
    ): InvestedEventFilter;
    Invested(
      bountyId?: PromiseOrValue<BigNumberish> | null,
      investor?: PromiseOrValue<string> | null,
      amount?: null
    ): InvestedEventFilter;

    "InvestmentsWithdrawn(uint256)"(
      bountyId?: PromiseOrValue<BigNumberish> | null
    ): InvestmentsWithdrawnEventFilter;
    InvestmentsWithdrawn(
      bountyId?: PromiseOrValue<BigNumberish> | null
    ): InvestmentsWithdrawnEventFilter;

    "InvestorPaymentAccepted(uint256,uint128)"(
      bountyId?: PromiseOrValue<BigNumberish> | null,
      payment?: null
    ): InvestorPaymentAcceptedEventFilter;
    InvestorPaymentAccepted(
      bountyId?: PromiseOrValue<BigNumberish> | null,
      payment?: null
    ): InvestorPaymentAcceptedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "StablecoinAddedToWhitelist(address)"(
      stablecoin?: PromiseOrValue<string> | null
    ): StablecoinAddedToWhitelistEventFilter;
    StablecoinAddedToWhitelist(
      stablecoin?: PromiseOrValue<string> | null
    ): StablecoinAddedToWhitelistEventFilter;

    "StablecoinRemovedFromWhitelist(address)"(
      stablecoin?: PromiseOrValue<string> | null
    ): StablecoinRemovedFromWhitelistEventFilter;
    StablecoinRemovedFromWhitelist(
      stablecoin?: PromiseOrValue<string> | null
    ): StablecoinRemovedFromWhitelistEventFilter;

    "WorkerAccepted(uint256,address)"(
      bountyId?: PromiseOrValue<BigNumberish> | null,
      worker?: PromiseOrValue<string> | null
    ): WorkerAcceptedEventFilter;
    WorkerAccepted(
      bountyId?: PromiseOrValue<BigNumberish> | null,
      worker?: PromiseOrValue<string> | null
    ): WorkerAcceptedEventFilter;

    "WorkerPaymentAccepted(uint256,uint128,uint128)"(
      bountyId?: PromiseOrValue<BigNumberish> | null,
      nativePay?: null,
      stablePay?: null
    ): WorkerPaymentAcceptedEventFilter;
    WorkerPaymentAccepted(
      bountyId?: PromiseOrValue<BigNumberish> | null,
      nativePay?: null,
      stablePay?: null
    ): WorkerPaymentAcceptedEventFilter;
  };

  estimateGas: {
    acceptInvestorPayment(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    acceptWorker(
      bountyId: PromiseOrValue<BigNumberish>,
      worker: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    acceptWorkerPayment(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addStablecoinToWhitelist(
      stablecoin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    calculateYieldPool(
      workerNativePay: PromiseOrValue<BigNumberish>,
      dailyYieldPercentage: PromiseOrValue<BigNumberish>,
      bountyCreationDate: PromiseOrValue<BigNumberish>,
      workerDeadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelBounty(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createBounty(
      workerStablePay: PromiseOrValue<BigNumberish>,
      workerNativePay: PromiseOrValue<BigNumberish>,
      exchangeRate: PromiseOrValue<BigNumberish>,
      nativeToken: PromiseOrValue<string>,
      stablecoin: PromiseOrValue<string>,
      dailyYieldPercentage: PromiseOrValue<BigNumberish>,
      workerDeadline: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAmountOfInvestments(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBounty(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getInvestment(
      bountyId: PromiseOrValue<BigNumberish>,
      investmentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    invest(
      bountyId: PromiseOrValue<BigNumberish>,
      stableAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    markBountyAsCompleted(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    removeStablecoinFromWhitelist(
      stablecoin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawInvestments(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptInvestorPayment(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    acceptWorker(
      bountyId: PromiseOrValue<BigNumberish>,
      worker: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    acceptWorkerPayment(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addStablecoinToWhitelist(
      stablecoin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    calculateYieldPool(
      workerNativePay: PromiseOrValue<BigNumberish>,
      dailyYieldPercentage: PromiseOrValue<BigNumberish>,
      bountyCreationDate: PromiseOrValue<BigNumberish>,
      workerDeadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelBounty(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createBounty(
      workerStablePay: PromiseOrValue<BigNumberish>,
      workerNativePay: PromiseOrValue<BigNumberish>,
      exchangeRate: PromiseOrValue<BigNumberish>,
      nativeToken: PromiseOrValue<string>,
      stablecoin: PromiseOrValue<string>,
      dailyYieldPercentage: PromiseOrValue<BigNumberish>,
      workerDeadline: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAmountOfInvestments(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBounty(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInvestment(
      bountyId: PromiseOrValue<BigNumberish>,
      investmentId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    invest(
      bountyId: PromiseOrValue<BigNumberish>,
      stableAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    markBountyAsCompleted(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeStablecoinFromWhitelist(
      stablecoin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawInvestments(
      bountyId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
