/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IWorkFi, IWorkFiInterface } from "../../contracts/IWorkFi";

const _abi = [
  {
    inputs: [],
    name: "AWorkerWasAlreadyAccepted",
    type: "error",
  },
  {
    inputs: [],
    name: "BountyDoesNotExist",
    type: "error",
  },
  {
    inputs: [],
    name: "BountyIsNotCancelled",
    type: "error",
  },
  {
    inputs: [],
    name: "BountyIsNotOngoing",
    type: "error",
  },
  {
    inputs: [],
    name: "InvestmentOpportunityIsClosed",
    type: "error",
  },
  {
    inputs: [],
    name: "InvestmentOpportunityIsStillOpen",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "maxPossibleAmount",
        type: "uint128",
      },
    ],
    name: "MaxInvestmentExceeded",
    type: "error",
  },
  {
    inputs: [],
    name: "NotAWhitelistedStablecoin",
    type: "error",
  },
  {
    inputs: [],
    name: "NotAnInvestor",
    type: "error",
  },
  {
    inputs: [],
    name: "NotRecruiter",
    type: "error",
  },
  {
    inputs: [],
    name: "NotTheWorker",
    type: "error",
  },
  {
    inputs: [],
    name: "RecruiterCannotInvest",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "required",
        type: "uint128",
      },
    ],
    name: "ThisAmountOfEthIsRequired",
    type: "error",
  },
  {
    inputs: [],
    name: "ValueShouldBeZeroIfNotPayingWithEth",
    type: "error",
  },
  {
    inputs: [],
    name: "WorkerCannotBeZero",
    type: "error",
  },
  {
    inputs: [],
    name: "WorkerCannotInvest",
    type: "error",
  },
  {
    inputs: [],
    name: "WorkerDeadlineExpired",
    type: "error",
  },
  {
    inputs: [],
    name: "WorkerHasBeenPaid",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "BountyCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "BountyCompleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "recruiter",
        type: "address",
      },
    ],
    name: "BountyCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "investor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "amount",
        type: "uint128",
      },
    ],
    name: "Invested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "InvestmentsWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "payment",
        type: "uint128",
      },
    ],
    name: "InvestorPaymentAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "stablecoin",
        type: "address",
      },
    ],
    name: "StablecoinAddedToWhitelist",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "stablecoin",
        type: "address",
      },
    ],
    name: "StablecoinRemovedFromWhitelist",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "worker",
        type: "address",
      },
    ],
    name: "WorkerAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "nativePay",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "stablePay",
        type: "uint128",
      },
    ],
    name: "WorkerPaymentAccepted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "acceptInvestorPayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "worker",
        type: "address",
      },
    ],
    name: "acceptWorker",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "acceptWorkerPayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "stablecoin",
        type: "address",
      },
    ],
    name: "addStablecoinToWhitelist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "initialValue",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "dailyYieldPercentage",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "daysBeforeInvestmentOpportunityCloses",
        type: "uint128",
      },
    ],
    name: "calculateTotalYield",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "workerNativePay",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "dailyYieldPercentage",
        type: "uint128",
      },
      {
        internalType: "uint256",
        name: "bountyCreationDate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "workerDeadline",
        type: "uint256",
      },
    ],
    name: "calculateYieldPool",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "cancelBounty",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "workerStablePay",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "workerNativePay",
        type: "uint128",
      },
      {
        internalType: "uint96",
        name: "exchangeRate",
        type: "uint96",
      },
      {
        internalType: "address",
        name: "nativeToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "stablecoin",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "dailyYieldPercentage",
        type: "uint128",
      },
      {
        internalType: "uint256",
        name: "workerDeadline",
        type: "uint256",
      },
    ],
    name: "createBounty",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "getAmountOfInvestments",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "getBounty",
    outputs: [
      {
        components: [
          {
            internalType: "uint128",
            name: "workerStablePay",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "workerNativePay",
            type: "uint128",
          },
          {
            internalType: "uint96",
            name: "exchangeRate",
            type: "uint96",
          },
          {
            internalType: "address",
            name: "stablecoin",
            type: "address",
          },
          {
            internalType: "address",
            name: "nativeToken",
            type: "address",
          },
          {
            internalType: "uint128",
            name: "dailyYieldPercentage",
            type: "uint128",
          },
          {
            internalType: "address",
            name: "worker",
            type: "address",
          },
          {
            internalType: "address",
            name: "recruiter",
            type: "address",
          },
          {
            internalType: "enum BountyStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "workerDeadline",
            type: "uint256",
          },
          {
            internalType: "uint128",
            name: "initialWorkerStablePay",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "initialWorkerNativePay",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "creationDate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "workerPaidAt",
            type: "uint256",
          },
        ],
        internalType: "struct BountyMetadata",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "investmentId",
        type: "uint256",
      },
    ],
    name: "getInvestment",
    outputs: [
      {
        components: [
          {
            internalType: "uint128",
            name: "stableAmount",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "creationDate",
            type: "uint256",
          },
        ],
        internalType: "struct IWorkFi.InvestmentMetadata",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        internalType: "uint128",
        name: "stableAmount",
        type: "uint128",
      },
    ],
    name: "invest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "markBountyAsCompleted",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "stablecoin",
        type: "address",
      },
    ],
    name: "removeStablecoinFromWhitelist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "withdrawInvestments",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IWorkFi__factory {
  static readonly abi = _abi;
  static createInterface(): IWorkFiInterface {
    return new utils.Interface(_abi) as IWorkFiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWorkFi {
    return new Contract(address, _abi, signerOrProvider) as IWorkFi;
  }
}
