/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IWorkFi, IWorkFiInterface } from "../../contracts/IWorkFi";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "acceptInvestorPayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "worker",
        type: "address",
      },
    ],
    name: "acceptWorker",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "acceptWorkerPayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "cancelBounty",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "workerStablePay",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "workerNativePay",
        type: "uint128",
      },
      {
        internalType: "uint96",
        name: "exchangeRate",
        type: "uint96",
      },
      {
        internalType: "address",
        name: "nativeToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "stablecoin",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "dailyYieldPercentage",
        type: "uint128",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "createBounty",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "getAmountOfInvestments",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "getBounty",
    outputs: [
      {
        components: [
          {
            internalType: "uint128",
            name: "workerStablePay",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "workerNativePay",
            type: "uint128",
          },
          {
            internalType: "uint96",
            name: "exchangeRate",
            type: "uint96",
          },
          {
            internalType: "address",
            name: "stablecoin",
            type: "address",
          },
          {
            internalType: "address",
            name: "nativeToken",
            type: "address",
          },
          {
            internalType: "uint128",
            name: "dailyYieldPercentage",
            type: "uint128",
          },
          {
            internalType: "address",
            name: "worker",
            type: "address",
          },
          {
            internalType: "address",
            name: "recruiter",
            type: "address",
          },
          {
            internalType: "enum BountyStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "workerDeadline",
            type: "uint256",
          },
          {
            internalType: "uint128",
            name: "initialWorkerStablePay",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "initialWorkerNativePay",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "creationDate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "workerPaidAt",
            type: "uint256",
          },
        ],
        internalType: "struct BountyMetadata",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "investmentId",
        type: "uint256",
      },
    ],
    name: "getInvestment",
    outputs: [
      {
        components: [
          {
            internalType: "uint128",
            name: "stableAmount",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "creationDate",
            type: "uint256",
          },
        ],
        internalType: "struct IWorkFi.InvestmentMetadata",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        internalType: "uint128",
        name: "stableAmount",
        type: "uint128",
      },
    ],
    name: "invest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "markBountyAsCompleted",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "withdrawInvestments",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IWorkFi__factory {
  static readonly abi = _abi;
  static createInterface(): IWorkFiInterface {
    return new utils.Interface(_abi) as IWorkFiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWorkFi {
    return new Contract(address, _abi, signerOrProvider) as IWorkFi;
  }
}
