/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type { MathUtils, MathUtilsInterface } from "../../contracts/MathUtils";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "percentage",
        type: "uint256",
      },
    ],
    name: "calculatePercentage",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x610248610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100355760003560e01c80632133e3b91461003a575b600080fd5b610054600480360381019061004f91906100a2565b61006a565b60405161006191906100ed565b60405180910390f35b6000612710828461007b9190610139565b6100859190610108565b905092915050565b60008135905061009c816101fb565b92915050565b600080604083850312156100b557600080fd5b60006100c38582860161008d565b92505060206100d48582860161008d565b9150509250929050565b6100e781610193565b82525050565b600060208201905061010260008301846100de565b92915050565b600061011382610193565b915061011e83610193565b92508261012e5761012d6101cc565b5b828204905092915050565b600061014482610193565b915061014f83610193565b9250817fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff04831182151516156101885761018761019d565b5b828202905092915050565b6000819050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601260045260246000fd5b61020481610193565b811461020f57600080fd5b5056fea26469706673582212202d0be0cd3af638ff6affdda72ffe25300a935f7a31468f391faa118a9631057f64736f6c63430008040033";

type MathUtilsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MathUtilsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MathUtils__factory extends ContractFactory {
  constructor(...args: MathUtilsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<MathUtils> {
    return super.deploy(overrides || {}) as Promise<MathUtils>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MathUtils {
    return super.attach(address) as MathUtils;
  }
  override connect(signer: Signer): MathUtils__factory {
    return super.connect(signer) as MathUtils__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MathUtilsInterface {
    return new utils.Interface(_abi) as MathUtilsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MathUtils {
    return new Contract(address, _abi, signerOrProvider) as MathUtils;
  }
}
